### ISSUE TITLE
Assignment 1 Submission

### ISSUE THREAD

**Issue by kroynesdal** [SES-5215-F2020/kroynesdal-quant#1]
.Rmd file and .html file are ready for grading.

**Comment by saratepfer** [comment]
Thank you, Kari! Nice work on this. Your unit of analysis, number of observations, and who's included in your population are all clearly stated. Technically I think you should specify that your population only includes properties of value, as you include the filter VALP > 0.

**Comments on Code**
line 7: you don't need to include this in your markdown file. It's fine to just run this line in your console.
line 33: you can start the code chunk with {r, results = 'hide'} to prevent your knitted file from including hundreds of lines of code.
