### ISSUE TITLE
Assignment 2 ready for grading

### ISSUE THREAD

**Issue by kroynesdal** [SES-5215-F2020/kroynesdal-quant#2]
Both the .Rmd and .html file are ready for grading.

Thank you!

**Comment by saratepfer** [comment]
Nice visualizations, Kari! Please note that many of the visualizations you produced were not required for this assignment (everything but the histograms), but they look great!

- For the categorical proportions, please run a t-test on each unique category to get its proportion and 95% confidence interval. These calculations should then be made into a table (probably most easily done using the tibble() function), which shows each category in a row, its proportion, and the high and low estimate of its proportion. Please see Catherine's example assignment for details or feel free to come by office hours to discuss.
- The above should be done for both categorical variables.
